layouts:
    - tall
    - wide
    - fullscreen
    - middle-wide
    - bsp

# Select column layout (override)
# assignng to some random key to override the default (SHIFT + OPTION + F)
select-column-layout:
  mod: mod1
  key: 9