#!/usr/bin/env bash
# Do not execute as root
if [ "$(id -u)" == "0" ]; then
   echo "Dude, ditch root." 1>&2
   exit 1
fi

set -e

pad='.........................'

# Finds file where script is stored
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for f in $(ls -a $DIR | grep '^\.[a-zA-Z0-9]\{2,\}')
do
  printf "Linking %s %s" $f "${pad:${#f}}"
  # Link every file in source directory to user's home
  ln -fs "$DIR/$f" ~/$f
  printf "done.\n"
done

# Mac OSX hack, requires bash_profile
ln -fs "$DIR/.bashrc" ~/.bash_profile
