#!/usr/bin/env bash


PAD='.........................'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# Do not execute as root
if [ "$(id -u)" == "0" ]; then
   echo "Dude, ditch root." 1>&2
   exit 1
fi

# Fail hard
set -e


# Check for flags
while test $# != 0
do
    case "$1" in
    -d) set -x ;;
    esac
    shift
done

_source() {
    source $1
}


_sync_folder() {
    SRC_DIR=$1
    rsync -rvzq $SRC_DIR ~/
}

_sync_file() {
    
    SRC=$1
    DEST=${2:-$SRC}
    
    printf "Linking $SRC to ~/$DEST" 
    rsync -avzq $SRC ~/$DEST
    printf " done.\n"
}

_sync() {

    if [ -d $1 ]; then
        _sync_folder $1 $2
    elif [ -f $1 ]; then
        _sync_file $1 $2
    fi   
}


_sync .bashrc
_sync .bashrc .bash_profile
_sync .emacs
_sync .vimrc
_sync .vim
_sync .tmux.conf

_source .bashrc
